CREATE OR REPLACE PROCEDURE getUserProperty(OID IN VARCHAR) AS
N INTEGER;
PROP_TYPE VARCHAR(200);
BEGIN
SELECT COUNT(*) INTO N FROM PROPERTY WHERE PROPERTY.OWNER_ID = OID;
IF N > 0 THEN 
FOR ITR IN (SELECT * FROM PROPERTY WHERE PROPERTY.OWNER_ID = OID)
LOOP
IF ITR.PROPERTY_TYPE = 'Residential' or ITR.PROPERTY_TYPE = 'RESIDENTIAL' OR ITR.PROPERTY_TYPE = 'residential' THEN
SELECT BEDROOM_COUNT,RES_TYPE INTO N,PROP_TYPE FROM RES_PROP WHERE RES_PROP.PROPERTYID = ITR.PROPERTYID;
ELSE
SELECT COM_TYPE INTO PROP_TYPE FROM COM_PROP WHERE COM_PROP.PROPERTYID = ITR.PROPERTYID;
END IF;
IF ITR.isRented = 1 THEN
DBMS_OUTPUT.PUT_LINE('PROPERTY ID: '||ITR.PROPERTYID|| ' (RENTED)');
ELSE 
DBMS_OUTPUT.PUT_LINE('PROPERTY ID: '||ITR.PROPERTYID|| ' (AVAILABLE)');
END IF;
DBMS_OUTPUT.PUT_LINE('ADDRESS: ' ||ITR.DOOR || ', '|| ITR.STREET||', ' ||ITR.LOCALITY ||', ' || ITR.CITY||', '||ITR.PINCODE||', ' ||ITR.STATE_NAME);
DBMS_OUTPUT.PUT_LINE('Year of Construction: '|| ITR.YEAR_OF_CONST);
DBMS_OUTPUT.PUT_LINE('Rent Per Month: '||ITR.CURRENT_RENT_PM);
DBMS_OUTPUT.PUT_LINE('Annual Hike: '||ITR.ANNUAL_HIKE);
DBMS_OUTPUT.PUT_LINE('Start Date: '||ITR.AVAIL_START_DATE || ' End Date: ' ||ITR.AVAIL_END_DATE);
DBMS_OUTPUT.PUT_LINE('Total Area: '||ITR.TOTAL_AREA);
DBMS_OUTPUT.PUT_LINE('Floor Count: '||ITR.FLOOR_COUNT);
IF ITR.PROPERTY_TYPE = 'Residential' or ITR.PROPERTY_TYPE = 'RESIDENTIAL' OR ITR.PROPERTY_TYPE = 'residential' THEN
DBMS_OUTPUT.PUT_LINE('Property Type: Residential');
DBMS_OUTPUT.PUT_LINE('No. Of bedrooms: '||N);
DBMS_OUTPUT.PUT_LINE('Residential Type: '||PROP_TYPE);
ELSE
DBMS_OUTPUT.PUT_LINE('Property Type: Commercial');
DBMS_OUTPUT.PUT_LINE('Commercial Type: '||PROP_TYPE);
end if;
END LOOP;
ELSE
DBMS_OUTPUT.PUT_LINE('You do not have any listed properties');
END IF;
end;
/