CREATE TABLE COM_PROP(
    PROPERTYID INTEGER CONSTRAINT COMM_UQ UNIQUE,
    COM_TYPE VARCHAR(200)
);
   
ALTER TABLE COM_PROP ADD CONSTRAINT COM_PROP_FK FOREIGN KEY(PROPERTYID) REFERENCES PROPERTY(PROPERTYID) on delete cascade;