CREATE TABLE PROPERTY_RENT(
    PROPERTYID INTEGER CONSTRAINT PROP_RENT_UQ UNIQUE,
    RENT_PM INTEGER NOT NULL,
    ANNUAL_HIKE FLOAT DEFAULT 0.0,
    AGENCY_COM FLOAT DEFAULT 0.05
);

ALTER TABLE PROPERTY_RENT ADD CONSTRAINT PROP_RENT_FK FOREIGN KEY(PROPERTYID) REFERENCES PROPERTY(PROPERTYID);