CREATE TABLE PROPERTY(
    PROPERTYID INTEGER PRIMARY KEY,
    OWNER_ID VARCHAR(50) NOT NULL,
    FLOOR_COUNT INTEGER,
    DOOR VARCHAR(200),
    STREET VARCHAR(200) NOT NULL,
    CITY VARCHAR(200) NOT NULL,
    STATE_NAME VARCHAR(200) NOT NULL,
    PINCODE VARCHAR(200) NOT NULL,
    YEAR_OF_CONST INTEGER,
    AVAIL_START_DATE DATE DEFAULT SYSDATE, 
    AVAIL_END_DATE DATE,
    CURRENT_RENT_PM INTEGER NOT NULL,
    LOCALITY VARCHAR(200),
    TOTAL_AREA INTEGER NOT NULL,
    isRented INTEGER DEFAULT 0,
    PROPERTY_TYPE VARCHAR(200),
    ANNUAL_HIKE FLOAT
);

ALTER TABLE PROPERTY ADD CONSTRAINT PROPERTY_OWNER_FK FOREIGN KEY(OWNER_ID) REFERENCES USERS(AADHARID) ON DELETE CASCADE;
