CREATE TABLE RES_PROP(
    PROPERTYID INTEGER CONSTRAINT RES_UQ UNIQUE,
    BEDROOM_COUNT INTEGER NOT NULL,
    RES_TYPE VARCHAR(200)
);

ALTER TABLE RES_PROP ADD CONSTRAINT RES_PROP_FK FOREIGN KEY(PROPERTYID) REFERENCES PROPERTY(PROPERTYID) on delete cascade;