CREATE TABLE TENANT_PROP_RENT(
    TENANTID VARCHAR(50) NOT NULL,
    RENT_PROPERTYID INTEGER NOT NULL,
    START_DATE DATE, 
    END_DATE DATE
);
ALTER TABLE TENANT_PROP_RENT ADD  CONSTRAINT TENANT_RENT_FK FOREIGN KEY(TENANTID) REFERENCES USERS(AADHARID);
ALTER TABLE TENANT_PROP_RENT ADD CONSTRAINT T_PROP_RENT_FK FOREIGN KEY(RENT_PROPERTYID) REFERENCES PROPERTY(PROPERTYID);