CREATE TABLE user_contact_detail(
    AADHARID VARCHAR(200),
    CONTACT VARCHAR(10),
    PRIMARY KEY(AADHARID,CONTACT)
);

ALTER TABLE user_contact_detail ADD CONSTRAINT CONTACT_FK FOREIGN KEY(AADHARID) REFERENCES USERS(AADHARID);