--insert into residential TABLE
CREATE OR REPLACE PROCEDURE RES_INSERT(PROP_ID IN INTEGER,RES_TYPE IN VARCHAR,BEDROOM_COUNT IN INTEGER) AS
BEGIN
INSERT INTO RES_PROP VALUES(PROP_ID,BEDROOM_COUNT,RES_TYPE);  
END;
/
-- insert into commercial
CREATE OR REPLACE PROCEDURE COMM_INSERT(PROP_ID IN INTEGER,COM_TYPE IN VARCHAR) AS
BEGIN
INSERT INTO COM_PROP VALUES(PROP_ID,COM_TYPE);  
END;
/
-- INSERT NEW PROPERTY AND DESIGNATE USER AS OWNER
create or replace procedure insertProperty(PROP_ID IN INTEGER,OWNER_ID IN VARCHAR,FLOOR_COUNT IN INTEGER, DOOR IN VARCHAR,STREET IN VARCHAR,CITY IN VARCHAR,STATE_NAME IN VARCHAR,PINCODE IN VARCHAR,YEAR_OF_CONST IN INTEGER,AVAIL_START_DATE IN DATE,AVAIL_END_DATE IN DATE,CURRENT_RENT_PM IN INTEGER,LOCALITY IN VARCHAR,ANNUAL_HIKE IN FLOAT,TOTAL_AREA IN INTEGER,PROP_TYPE IN VARCHAR,RES_TYPE IN VARCHAR DEFAULT NULL,COM_TYPE IN VARCHAR DEFAULT NULL,BEDROOM_COUNT IN INTEGER DEFAULT 0) AS
BEGIN
INSERT INTO PROPERTY VALUES(PROP_ID,OWNER_ID,FLOOR_COUNT,DOOR,STREET,CITY,STATE_NAME,PINCODE,YEAR_OF_CONST,AVAIL_START_DATE,AVAIL_END_DATE,CURRENT_RENT_PM,LOCALITY,0,TOTAL_AREA,PROP_TYPE,ANNUAL_HIKE);
UPDATE USERS SET ISOWNER = 1 WHERE AADHARID = OWNER_ID;
IF PROP_TYPE = 'Residential' or PROP_TYPE = 'RESIDENTIAL' OR PROP_TYPE = 'residential' THEN
RES_INSERT(PROP_ID,RES_TYPE,BEDROOM_COUNT);
ELSIF PROP_TYPE = 'COMMERCIAL' or PROP_TYPE = 'commercial' OR PROP_TYPE = 'Commercial' THEN
COMM_INSERT(PROP_ID,COM_TYPE);
ELSE
DBMS_OUTPUT.PUT_LINE('PROPERTY TYPE INVALID!');
END IF;
END;
/

--DELETE PROPERTY BY USER
CREATE OR REPLACE PROCEDURE deletePropertyByUser(PROP_ID IN INTEGER,OW_ID IN VARCHAR) AS
PROPERTY_COUNT INTEGER;
BEGIN
SELECT COUNT(*) INTO PROPERTY_COUNT FROM PROPERTY WHERE OWNER_ID = OW_ID;
IF PROPERTY_COUNT > 0 THEN
DELETE FROM PROPERTY WHERE PROPERTYID = PROP_ID AND OWNER_ID = OW_ID;
PROPERTY_COUNT := PROPERTY_COUNT-1;
IF PROPERTY_COUNT = 0 THEN
UPDATE USERS SET ISOWNER = 0 WHERE AADHARID = OW_ID;
END IF;
ELSE 
DBMS_OUTPUT.PUT_LINE('YOU HAVE NO LISTED PROPERTIES');
END IF;
END;
/





